{{- $dashboard:=string "config.dashboard" .Vars -}}

[serversTransport]
  insecureSkipVerify = true
[entryPoints]
    [entryPoints.http]
    address = ":8080"
    [entryPoints.https]
    address = ":443"
    [entryPoints.traefik]
    address = ":8081"
[api]
    dashboard = {{ $dashboard }}
    insecure  = true
# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false
    [providers.consulCatalog.endpoint]
      address = "127.0.0.1:8500"
      scheme  = "http"